services:
  - type: web
    name: almothanna-backend
    region: oregon
    plan: free
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        fromSecret: jwt-secret